# config_hyperopt.yml
# Configuration for a full hyperparameter optimization search using Hyperopt.

# Global settings for the hyperopt run
global_params:
  verbose: 1 # Less verbose for multiple runs
  error_raise: False # Don't stop the search on a single trial failure

# Experiment settings for the hyperopt run
experiment:
  # Base directory for storing all experiment results
  experiments_base_dir: "HFE_ML_experiments"
  # A descriptive name for this experiment batch
  additional_naming: "HFE_ML_Hyperopt_Grid"

# Data settings for the hyperopt run
data:
  # Path to the dataset
  file_path: "test_data_hfe_1yr_m_small_multiclass.csv"
  # List of substrings to identify columns to drop
  drop_term_list:
    - 'chrom'
    - 'hfe'
    - 'phlebo'
  # Set to true to iterate over all 'outcome_var_' columns in the dataset
  multiple_outcomes: True

# Models to be used during the hyperopt search
models:
  LogisticRegression_class: true
  knn_classifiers_class: true
  quadratic_discriminant_analysis_class: true
  SVC_class: true
  XGB_class_class: true
  mlp_classifier_class: true
  RandomForestClassifier_class: true
  GradientBoostingClassifier_class: true
  CatBoost_class: true
  GaussianNB_class: true
  H2O_class: false # H2O AutoML
  H2O_GBM_class: true
  H2O_DRF_class: true
  H2O_DeepLearning_class: true
  H2O_GLM_class: true
  H2O_NaiveBayes_class: true
  H2O_RuleFit_class: true
  H2O_XGBoost_class: true
  H2O_StackedEnsemble_class: true
  H2O_GAM_class: true
  LightGBMClassifierWrapper: true
  adaboost_class: true
  NeuralNetworkClassifier_class: true
  TabTransformer_class: false
  # Set the following to true if a GPU is available and configured
  kerasClassifier_class: false
  knn__gpu_wrapper_class: false

# This section defines the parameter search space for Hyperopt.
# The structure uses lists of options, which will be parsed into hp.choice.
hyperopt_search_space:
  resample: ['undersample', 'oversample', null]
  scale: [True, False]
  feature_n: [100, 95, 75, 50, 25, 5]
  param_space_size: ['medium', 'xsmall']
  percent_missing: [99, 95, 80]
  correlation_threshold: [0.98, 0.85, 0.5, 0.25]
  feature_selection_method: ['anova', 'markov_blanket']
  outcome_var_n: ['1'] # Default, will be overridden if multiple_outcomes is true

  # Embedding hyperparameters
  use_embedding: [True, False]
  embedding_method: ['pca', 'svd']
  embedding_dim: [32, 64, 128]
  scale_features_before_embedding: [True, False]

  # Feature group toggles
  data:
    age: [True, False]
    sex: [True, False]
    bmi: [True]
    ethnicity: [True, False]
    bloods: [True, False]
    diagnostic_order: [True, False]
    drug_order: [True, False]
    annotation_n: [True, False]
    meta_sp_annotation_n: [True, False]
    annotation_mrc_n: [True, False]
    meta_sp_annotation_mrc_n: [True, False]
    core_02: [False]
    bed: [False]
    vte_status: [True]
    hosp_site: [True]
    core_resus: [False]
    news: [False]
    date_time_stamp: [False]
    appointments: [False]

# Hyperopt-specific settings
hyperopt_settings:
  max_evals: 2 # Number of iterations per outcome variable