class OutcomeList:

    def __init__(self) -> None:

        self.all_outcome_list = [
            "Hemochromatosis (disorder)_count",
            "Hemochromatosis (disorder)_count_subject_present",
            "Hemochromatosis (disorder)_count_relative_present",
            "Bronze cirrhosis (disorder)_count",
            "Bronze cirrhosis (disorder)_count_subject_present",
            "Bronze cirrhosis (disorder)_count_relative_present",
            "Bronze diabetes (disorder)_count",
            "Bronze diabetes (disorder)_count_subject_present",
            "Bronze diabetes (disorder)_count_relative_present",
            "Hereditary hemochromatosis (disorder)_count",
            "Hereditary hemochromatosis (disorder)_count_subject_present",
            "Hereditary hemochromatosis (disorder)_count_relative_present",
            "Autosomal dominant hereditary hemochromatosis (disorder)_count",
            "Autosomal dominant hereditary hemochromatosis (disorder)_count_subject_present",
            "Autosomal dominant hereditary hemochromatosis (disorder)_count_relative_present",
            "1186847009_count",
            "1186847009_count_subject_present",
            "1186847009_count_relative_present",
            "Hemochromatosis type 3 (disorder)_count",
            "Hemochromatosis type 3 (disorder)_count_subject_present",
            "Hemochromatosis type 3 (disorder)_count_relative_present",
            "Juvenile hemochromatosis (disorder)_count",
            "Juvenile hemochromatosis (disorder)_count_subject_present",
            "Juvenile hemochromatosis (disorder)_count_relative_present",
            "1186849007_count",
            "1186849007_count_subject_present",
            "1186849007_count_relative_present",
            "1186844002_count",
            "1186844002_count_subject_present",
            "1186844002_count_relative_present",
            "Idiopathic hemochromatosis (disorder)_count",
            "Idiopathic hemochromatosis (disorder)_count_subject_present",
            "Idiopathic hemochromatosis (disorder)_count_relative_present",
            "Neonatal hemochromatosis (disorder)_count",
            "Neonatal hemochromatosis (disorder)_count_subject_present",
            "Neonatal hemochromatosis (disorder)_count_relative_present",
            "Primary hemochromatosis (disorder)_count",
            "Primary hemochromatosis (disorder)_count_subject_present",
            "Primary hemochromatosis (disorder)_count_relative_present",
            "Secondary hemochromatosis (disorder)_count",
            "Secondary hemochromatosis (disorder)_count_subject_present",
            "Secondary hemochromatosis (disorder)_count_relative_present",
            "African nutritional hemochromatosis (disorder)_count",
            "African nutritional hemochromatosis (disorder)_count_subject_present",
            "African nutritional hemochromatosis (disorder)_count_relative_present",
            "Erythropoietic hemochromatosis (disorder)_count",
            "Erythropoietic hemochromatosis (disorder)_count_subject_present",
            "Erythropoietic hemochromatosis (disorder)_count_relative_present",
            "Hemochromatosis following repeated red blood cell transfusion (disorder)_count",
            "Hemochromatosis following repeated red blood cell transfusion (disorder)_count_subject_present",
            "Hemochromatosis following repeated red blood cell transfusion (disorder)_count_relative_present",
            "Homozygous For The C . 845G A P . Cys282Tyr Variant_count",
            "Homozygous For The C . 845G A P . Cys282Tyr Variant_count_subject_present",
            "Homozygous For The C . 845G A P . Cys282Tyr Variant_count_relative_present",
            "Hfe Ph63D Heterozygous Normal Variant_count",
            "Hfe Ph63D Heterozygous Normal Variant_count_subject_present",
            "Hfe Ph63D Heterozygous Normal Variant_count_relative_present",
            "Homozygous For Haemochromatosis Gene Mutation_count",
            "Homozygous For Haemochromatosis Gene Mutation_count_subject_present",
            "Homozygous For Haemochromatosis Gene Mutation_count_relative_present",
            "Homozygous For The C . 845G A P . Cys282Tyr Variant_count",
            "Homozygous For The C . 845G A P . Cys282Tyr Variant_count_subject_present",
            "Homozygous For The C . 845G A P . Cys282Tyr Variant_count_relative_present",
            "Homozygous For The C2828Y Mutation Of The Hfe Gene_count",
            "Homozygous For The C2828Y Mutation Of The Hfe Gene_count_subject_present",
            "Homozygous For The C2828Y Mutation Of The Hfe Gene_count_relative_present",
            "Hfe Ph63D Heterozygous Normal Variant_count",
            "Hfe Ph63D Heterozygous Normal Variant_count_subject_present",
            "Hfe Ph63D Heterozygous Normal Variant_count_relative_present",
            "Homozygous For The H63D Mutation_count",
            "Homozygous For The H63D Mutation_count_subject_present",
            "Homozygous For The H63D Mutation_count_relative_present",
            "This Patient Is A Carrier For The Mutation In The Hfe Gene At Position 282 C Y This Patient Is A Carrier For The Mutation In The Hfe Gene At Position 63 H D_count",
            "This Patient Is A Carrier For The Mutation In The Hfe Gene At Position 282 C Y This Patient Is A Carrier For The Mutation In The Hfe Gene At Position 63 H D_count_subject_present",
            "This Patient Is A Carrier For The Mutation In The Hfe Gene At Position 282 C Y This Patient Is A Carrier For The Mutation In The Hfe Gene At Position 63 H D_count_relative_present",
            "Homozygous For Haemochromatosis Gene Mutation_count",
            "Homozygous For Haemochromatosis Gene Mutation_count_subject_present",
            "Homozygous For Haemochromatosis Gene Mutation_count_relative_present",
            "Heterozygous For The Haemochromatosis Gene_count",
            "Heterozygous For The Haemochromatosis Gene_count_subject_present",
            "Heterozygous For The Haemochromatosis Gene_count_relative_present",
            "Haemochromatosis gene screening test (observable entity)_count",
            "Haemochromatosis gene screening test (observable entity)_count_subject_present",
            "Haemochromatosis gene screening test (observable entity)_count_relative_present",
            "Carrier of hemochromatosis (finding)_count",
            "Carrier of hemochromatosis (finding)_count_subject_present",
            "Carrier of hemochromatosis (finding)_count_relative_present",
            "Hemochromatosis gene screening test (procedure)_count",
            "Hemochromatosis gene screening test (procedure)_count_subject_present",
            "Hemochromatosis gene screening test (procedure)_count_relative_present",
            "Iron overload (disorder)_count",
            "Iron overload (disorder)_count_subject_present",
            "Iron overload (disorder)_count_relative_present",
            "Family history of hemochromatosis (situation)_count",
            "Family history of hemochromatosis (situation)_count_subject_present",
            "Family history of hemochromatosis (situation)_count_relative_present",
            "Hemochromatosis (disorder)_count_subject_not_present",
            "Hemochromatosis (disorder)_count_relative_not_present",
            "Bronze cirrhosis (disorder)_count_subject_not_present",
            "Bronze cirrhosis (disorder)_count_relative_not_present",
            "Bronze diabetes (disorder)_count_subject_not_present",
            "Bronze diabetes (disorder)_count_relative_not_present",
            "Hereditary hemochromatosis (disorder)_count_subject_not_present",
            "Hereditary hemochromatosis (disorder)_count_relative_not_present",
            "Autosomal dominant hereditary hemochromatosis (disorder)_count_subject_not_present",
            "Autosomal dominant hereditary hemochromatosis (disorder)_count_relative_not_present",
            "1186847009_count_subject_not_present",
            "1186847009_count_relative_not_present",
            "Hemochromatosis type 3 (disorder)_count_subject_not_present",
            "Hemochromatosis type 3 (disorder)_count_relative_not_present",
            "Juvenile hemochromatosis (disorder)_count_subject_not_present",
            "Juvenile hemochromatosis (disorder)_count_relative_not_present",
            "1186849007_count_subject_not_present",
            "1186849007_count_relative_not_present",
            "1186844002_count_subject_not_present",
            "1186844002_count_relative_not_present",
            "Idiopathic hemochromatosis (disorder)_count_subject_not_present",
            "Idiopathic hemochromatosis (disorder)_count_relative_not_present",
            "Neonatal hemochromatosis (disorder)_count_subject_not_present",
            "Neonatal hemochromatosis (disorder)_count_relative_not_present",
            "Primary hemochromatosis (disorder)_count_subject_not_present",
            "Primary hemochromatosis (disorder)_count_relative_not_present",
            "Secondary hemochromatosis (disorder)_count_subject_not_present",
            "Secondary hemochromatosis (disorder)_count_relative_not_present",
            "African nutritional hemochromatosis (disorder)_count_subject_not_present",
            "African nutritional hemochromatosis (disorder)_count_relative_not_present",
            "Erythropoietic hemochromatosis (disorder)_count_subject_not_present",
            "Erythropoietic hemochromatosis (disorder)_count_relative_not_present",
            "Hemochromatosis following repeated red blood cell transfusion (disorder)_count_subject_not_present",
            "Hemochromatosis following repeated red blood cell transfusion (disorder)_count_relative_not_present",
            "Homozygous For The C . 845G A P . Cys282Tyr Variant_count_subject_not_present",
            "Homozygous For The C . 845G A P . Cys282Tyr Variant_count_relative_not_present",
            "Hfe Ph63D Heterozygous Normal Variant_count_subject_not_present",
            "Hfe Ph63D Heterozygous Normal Variant_count_relative_not_present",
            "Homozygous For Haemochromatosis Gene Mutation_count_subject_not_present",
            "Homozygous For Haemochromatosis Gene Mutation_count_relative_not_present",
            "Homozygous For The C . 845G A P . Cys282Tyr Variant_count_subject_not_present",
            "Homozygous For The C . 845G A P . Cys282Tyr Variant_count_relative_not_present",
            "Homozygous For The C2828Y Mutation Of The Hfe Gene_count_subject_not_present",
            "Homozygous For The C2828Y Mutation Of The Hfe Gene_count_relative_not_present",
            "Hfe Ph63D Heterozygous Normal Variant_count_subject_not_present",
            "Hfe Ph63D Heterozygous Normal Variant_count_relative_not_present",
            "Homozygous For The H63D Mutation_count_subject_not_present",
            "Homozygous For The H63D Mutation_count_relative_not_present",
            "This Patient Is A Carrier For The Mutation In The Hfe Gene At Position 282 C Y This Patient Is A Carrier For The Mutation In The Hfe Gene At Position 63 H D_count_subject_not_present",
            "This Patient Is A Carrier For The Mutation In The Hfe Gene At Position 282 C Y This Patient Is A Carrier For The Mutation In The Hfe Gene At Position 63 H D_count_relative_not_present",
            "Homozygous For Haemochromatosis Gene Mutation_count_subject_not_present",
            "Homozygous For Haemochromatosis Gene Mutation_count_relative_not_present",
            "Heterozygous For The Haemochromatosis Gene_count_subject_not_present",
            "Heterozygous For The Haemochromatosis Gene_count_relative_not_present",
            "Haemochromatosis gene screening test (observable entity)_count_subject_not_present",
            "Haemochromatosis gene screening test (observable entity)_count_relative_not_present",
            "Carrier of hemochromatosis (finding)_count_subject_not_present",
            "Carrier of hemochromatosis (finding)_count_relative_not_present",
            "Hemochromatosis gene screening test (procedure)_count_subject_not_present",
            "Hemochromatosis gene screening test (procedure)_count_relative_not_present",
            "Iron overload (disorder)_count_subject_not_present",
            "Iron overload (disorder)_count_relative_not_present",
            "Family history of hemochromatosis (situation)_count_subject_not_present",
            "Family history of hemochromatosis (situation)_count_relative_not_present",
            "Homozygote For The C282Y Mutation_count_relative_present",
            "Homozygote For The C282Y Mutation_count_relative_not_present",
            "Homozygote For The C282Y Mutation_count_subject_present",
            "Homozygote For The C282Y Mutation_count_subject_not_present",
            "Homozygote For The C282Y Mutation_count",
            "Therapeutic phlebotomy (procedure)_count_relative_not_present_mrc_cs",
            "Therapeutic phlebotomy (procedure)_count_subject_present_mrc_cs",
            "Therapeutic phlebotomy (procedure)_count_subject_not_present_mrc_cs",
            "Therapeutic phlebotomy (procedure)_count_mrc_cs",
            "Phlebotomy (procedure)_count_subject_present",
            "Phlebotomy (procedure)_count",
            "Phlebotomy (procedure)_count_subject_not_present",
            "Phlebotomy (procedure)_count_relative_not_present",
            "Phlebotomy (procedure)_count_relative_not_present_mrc_cs",
            "Phlebotomy (procedure)_count_subject_not_present_mrc_cs",
            "Phlebotomy (procedure)_count_subject_present_mrc_cs",
            "Phlebotomy (procedure)_count_mrc_cs",
            "Seen by practice phlebotomist (finding)_count_relative_not_present",
            "Seen by practice phlebotomist (finding)_count",
            "Seen by practice phlebotomist (finding)_count_subject_present",
            "Seen by practice phlebotomist (finding)_count_subject_not_present",
            "Iron overload (disorder)_count_relative_not_present",
            "Iron overload (disorder)_count_subject_not_present",
            "Iron overload (disorder)_count",
            "Iron overload (disorder)_count_subject_present",
        ]
